[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "10.15.0"
  # TEMPORARY while you stabilize lockfile; remove later:
  # PNPM_FLAGS = "--no-frozen-lockfile"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"

# Optional domain canonicalization to www.alyandandyz.com
[[redirects]]
  from = "/*"
  to = "https://www.alyandandyz.com/:splat"
  status = 301
  force = true
  conditions = { Host = ["alyandandyz.com", "aliandandyz.com"] }
