[build]
  command = "pnpm build"
  publish = ".next"

# (Option A) If you keep the plugin in package.json, you can KEEP this block:
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects (optional but nice)
[[redirects]]
  from = "http://alyandandyz.com/*"
  to = "https://alyandandyz.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.alyandandyz.com/*"
  to = "https://alyandandyz.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.alyandandyz.com/*"
  to = "https://alyandandyz.com/:splat"
  status = 301
  force = true
