[build]
  command = "npm run build"
  publish  = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

# Optional: ignore build if only docs changed
#[build]
#  ignore = "git diff --quiet HEAD^ HEAD ./docs"
