[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Force HTTPS + canonical apex
[[redirects]]
  from = "http://alyandandyz.com/*"
  to = "https://alyandandyz.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.alyandandyz.com/*"
  to = "https://alyandandyz.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.alyandandyz.com/*"
  to = "https://alyandandyz.com/:splat"
  status = 301
  force = true
